guy_cnet_homepage:
    pattern:  /Home
    defaults: { _controller: GuyCnetBundle:Default:index }

guy_cnet_about:
    pattern:  /About
    defaults: { _controller: GuyCnetBundle:About:index }

guy_cnet_contact:
    pattern:  /Resume
    defaults: { _controller: GuyCnetBundle:Resume:index }
